#%RAML 1.0
title: Users CRUD API
baseUri: http://localhost:4000
mediaType: application/json

# Possible types
types:
    User:
        type: object
        properties:
            lastName: string
            firstName: string
            email: string
            password: string

# Routes
/users:
    description: User management
    get:
        description: List of all users
    post:
        description: Create a user
        body:
            type: User

    /{id}:
        get:
            description: Search a user

        put:
            description: Update a user
            body:
                type: User

        delete:
            description: Delete a user